### PR TITLE
Catch exceptions when accessing `indexedDB` and `localStorage`

### PR DESCRIPTION
**Pull request by joneschrisg**
In some browsers in some contexts, just accessing `window.indexedDB` and `window.localStorage` can throw exceptions.  Ignore those exceptions so that ImmortalDB continues to work.

Here's the QA procedure I ran on this PR:
1. `npm run format`
1. `npm run lint`: result was clean
1. `npm run build`
1. `npm run start`
1. Checked that setting, getting, and removing a key works across cookies, IndexedDB, and localStorage.

I committed the artifacts produced by `npm run build` --- let me know if that's done by a separate release procedure.

Thanks!!

### CODE REVIEW

**Comment by gruns** [comment]
Right on, brother. Awesome PR.

For my own notes, which browser(s) raise on just touching `window.indexedDB` and/or `window.localStorage`? Brave with the latter?

**Comment by joneschrisg** [comment]
Definitely Brave with `window.localStorage`.  Upstream Chrome can be configured similarly.  I don't recall whether `window.indexedDB` raised too, or we added it defensively; I believe it was defensive.

**Comment by gruns** [comment]
Merged! This will roll out in the next version.

One note: of

```Here's the QA procedure I ran on this PR:

npm run format
npm run lint: result was clean
npm run build
npm run start
Checked that setting, getting, and removing a key works across cookies, IndexedDB, and localStorage.```

what could have been better explained or better? Or, in other words, how would you improve the dev + testing loop (beyond automated tests)?

Thank you again, Chris. Don't hesitate to let me know if there's anything else I can do for you.

**Comment by joneschrisg** [comment]
Thanks!!

> what could have been better explained or better? Or, in other words, how would you improve the dev + testing loop (beyond automated tests)?

Automated tests are always great, of course :).  Here are two smaller suggestions:

* Create [GitHub actions](https://github.com/features/actions) to automate the lint and build checks.  That's not full automated testing of course, but pretty good effort/reward tradeoff because they're low effort.
* For the remaining manual checks, and general style and process guidelines, create a [`CONTRIBUTING.md`](https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors).  I would recommend listing the manual QA procedure explicitly as a sequence of steps contributors should follow, with expected results.

**Pull request merged**
