### PR TITLE
Update package.json to import transpiled version

### PR DESCRIPTION
**Pull request by mikheevm**
I got an error when using Jest because it was using the ES6 Version of the package and it failed to parse "import" token.
I think it should use transpiled version by default.

### CODE REVIEW

**Comment by mikheevm** [comment]
Actually this breaks everything. For some reason, the exports are empty. Any ideas on how to fix it?

**Comment by panstav** [comment]
This wouldn't help because ImmortalDB is dependent on other non-transpiled packages 😒

**Comment by gruns** [comment]
Which other non-transpiled packages?

ImmortalDB is already transpiled to `@babel/preset-env` via Babel, with
dependendencies excluded

```js
test: /\.m?js$/,
exclude: /(node_modules|bower_components)/,
use: {
    loader: 'babel-loader',
    options: {
        presets: [['@babel/preset-env', {
            useBuiltIns: 'usage',
        }]]
    }
}
```

Dependencies can always be transpiled, too.

**Comment by mikheevm** [comment]
Hey @gruns, I've update the PR:
- set `libraryTarget` to 'umd', so the transpiled version can be required via CommonJS / ES imports. Webpack docs: https://webpack.js.org/guides/author-libraries/#expose-the-library
- Added `module` entry to `package.json` for newer versions of node.js
- Removed unused `webpack` require in `webpack.config.js`

**Comment by mikheevm** [comment]
Tested my changes - works perfectly. However, I'm not sure if it will work with the `<script src="..." />`

**Comment by gruns** [comment]
I'll test this shortly and if all green lights: merge.

**Comment by mikheevm** [comment]
@gruns Happy New Year :) Any updates?

**Comment by gruns** [comment]
@mikheevm Thank you for the bump. Sincerely. Startup life keeps me busy.

I'll look into this.

**Comment by gruns** [comment]
@mikheevm Merged! Huge thank you for your PR, patches, work, and pings. Sincerely.

Thank you again, Mikhail. Don't hesitate to let me know if there's anything I can do for you.

**Pull request merged**
