### PR TITLE
Improve TypeScript typings

### PR DESCRIPTION
**Pull request by coolreader18**
Define a `Store` interface and each of the provided `Store` classes individually.

### CODE REVIEW

**Comment by alienriver49** [comment]
This would be great! Can't use this library currently because the typings don't include the stores I need and that will cause the build to fail. One small change (which follows your first commit); change the session and local storage stores to extend the storage api wrapper. So:

```
export class LocalStorageStore implements StorageApiWrapper {}
export class SessionStorageStore implements StorageApiWrapper {}
```

becomes

```
export class LocalStorageStore extends StorageApiWrapper {}
export class SessionStorageStore extends StorageApiWrapper {}
```

Just my two cents!

**Comment by coolreader18** [comment]
I think you checked the first commit, in the second one I did change it to `extends`.

**Comment by alienriver49** [comment]
D'oh! You are right, I did get the commits mixed up, looks great!

**Comment by coolreader18** [comment]
This pull request closed itself for some reason, so I opened #13.

**Comment by gruns** [comment]
Awesome.

I'll merge this shortly.

**Pull request closed without merging**
