### PR TITLE
Configure cookie attributes

### PR DESCRIPTION
**Pull request by zproxyz**
Changes:
-  `cookie-store.js`: Adding static method `setStoreOptions`
-  `immortal-db.d.ts`: Update types

This PR resolves issue #35

### CODE REVIEW

**Comment by zproxyz** [comment]
@gruns Hello, check this PR, please.

**Comment by gruns** [comment]
@zproxyz Thank you for the bump and *awesome* PR.

I actually started a similar cookie overhaul last week, before this PR. I will finish that shortly.

I'd like your help with the TS type definitions once committed, if you can help with that.

**Comment by gruns** [comment]
@zproxyz Committed!

If you have a few minutes, can you take a look at https://github.com/gruns/ImmortalDB/commit/e2ce22adef1184cd3a257b281f4452e4496b7c13 and update the TS type defs?

Thank you!

**Comment by gruns** [comment]
@zproxyz Updated: https://github.com/gruns/ImmortalDB/commit/f9705c99eac0cc73bd539215d58c5b5436aab817

**Comment by zproxyz** [comment]
@gruns I've checked your updates, some notes:
- https://github.com/gruns/ImmortalDB/commit/e2ce22adef1184cd3a257b281f4452e4496b7c13#r41623687
- https://github.com/gruns/ImmortalDB/commit/e2ce22adef1184cd3a257b281f4452e4496b7c13#r41623655
- https://github.com/gruns/ImmortalDB/commit/f9705c99eac0cc73bd539215d58c5b5436aab817#r41623739

**Comment by gruns** [comment]
Fixed in v1.1.0.

Huge thank you, @zproxyz, for all your time, help, and input here. I added you to the changelog for all your help.

**Pull request closed without merging**
